export default [
  { id: 1, sound: "Sound 1" },
  { id: 2, sound: "Sound 2" },
  { id: 3, sound: "Sound 3" },
  { id: 4, sound: "Sound 4" },
  { id: 5, sound: "Sound 5" },
  { id: 6, sound: "Sound 6" },
  { id: 7, sound: "Sound 1" },
  { id: 8, sound: "Sound 2" },
  { id: 9, sound: "Sound 3" },
  { id: 10, sound: "Sound 4" },
  { id: 11, sound: "Sound 5" },
  { id: 12, sound: "Sound 6" },
  { id: 13, sound: "Sound 1" },
  { id: 14, sound: "Sound 2" },
  { id: 15, sound: "Sound 3" },
  { id: 16, sound: "Sound 4" },
  { id: 17, sound: "Sound 5" },
  { id: 18, sound: "Sound 6" },
];
